### ISSUE TITLE
[suggestion] Add index link output

### ISSUE THREAD

**Issue by Topkek6969** [CoolFool/Ravager#10]
Would be great if you can add index link as well as drive link as output ones the upload is finished.

**Comment by CoolFool** [comment]
Regarding index link you mean hosting your own like with GDIndex, Goindex and using their url to generate the link, For example https://example123.qwerty.workers.dev/<file_path>, That should be possible but it should be per account cause ravager supports multiple accounts

I will look into it and see when I can add it, but if you want that the worker code be generated then it will take time cause I have to look into adding an endpoint for getting the google api credentials securely to the worker cause every account will have its own randomly generated endpoint.

Regarding drive link I will add it when I add index link support.

**Comment by Topkek6969** [comment]
> Regarding index link you mean hosting your own like with GDIndex, Goindex and using their url to generate the link, For example https://example123.qwerty.workers.dev/<file_path>, That should be possible but it should be per account cause ravager supports multiple accounts
> 
> I will look into it and see when I can add it, but if you want that the worker code be generated then it will take time cause I have to look into adding an endpoint for getting the google api credentials securely to the worker cause every account will have its own randomly generated endpoint.
> 
> Regarding drive link I will add it when I add index link support.

Never mind then, if it's that much amount of work then it's not worth it. Anyways, its just a suggestion, will close this issue now :)
