### ISSUE TITLE
Err on render

### ISSUE THREAD

**Issue by devillD** [CoolFool/Ravager#12]
"2022-05-31 17:52:48,123 — /app/ravager/housekeeping.py — INFO — <module>:11 — Database setup at sqlite:////app/database/ravager.db?check_same_thread=False"
May 31 11:52:48 PM  "2022-05-31 17:52:48,132 — /app/ravager/housekeeping.py — INFO — <module>:13 — 0"
May 31 11:52:48 PM  "2022-05-31 17:52:48,253 — /app/ravager/housekeeping.py — INFO — <module>:49 — True"
May 31 11:52:48 PM  "2022-05-31 17:52:48,253 — /app/ravager/housekeeping.py — INFO — <module>:50 — aria2c started"
May 31 11:53:01 PM  "2022-05-31 17:53:01,928 — /app/ravager/housekeeping.py — INFO — <module>:11 — Database setup at sqlite:////app/database/ravager.db?check_same_thread=False"
May 31 11:53:01 PM  "2022-05-31 17:53:01,935 — /app/ravager/housekeeping.py — INFO — <module>:13 — 0"
May 31 11:53:02 PM  "2022-05-31 17:53:02,002 — /app/ravager/housekeeping.py — INFO — <module>:49 — True"
May 31 11:53:02 PM  "2022-05-31 17:53:02,003 — /app/ravager/housekeeping.py — INFO — <module>:50 — aria2c started"
May 31 11:53:09 PM  No messages purged from 1 queue.
May 31 11:53:10 PM  "2022-05-31 17:53:10,002 — /app/ravager/services/aria/handler.py — INFO — <module>:100 — Started listening to aria2 notifications"
May 31 11:53:20 PM  [2022-05-31 17:53:20 +0000] [14] [INFO] Starting gunicorn 20.1.0
May 31 11:53:20 PM  [2022-05-31 17:53:20 +0000] [14] [INFO] Listening at: http://0.0.0.0:10000 (14)
May 31 11:53:20 PM  [2022-05-31 17:53:20 +0000] [14] [INFO] Using worker: sync
May 31 11:53:20 PM  [2022-05-31 17:53:20 +0000] [15] [INFO] Booting worker with pid: 15
May 31 11:53:23 PM  No messages purged from 1 queue.
May 31 11:53:23 PM  "2022-05-31 17:53:23,900 — /app/ravager/services/aria/handler.py — INFO — <module>:100 — Started listening to aria2 notifications"
May 31 11:53:34 PM  [2022-05-31 17:53:34 +0000] [15] [INFO] Starting gunicorn 20.1.0
May 31 11:53:34 PM  [2022-05-31 17:53:34 +0000] [15] [ERROR] Connection in use: ('0.0.0.0', 6801)
May 31 11:53:34 PM  [2022-05-31 17:53:34 +0000] [15] [ERROR] Retrying in 1 second.
May 31 11:53:35 PM  /opt/pysetup/.venv/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
May 31 11:53:35 PM  absolutely not recommended!
May 31 11:53:35 PM  
May 31 11:53:35 PM  Please specify a different user using the --uid option.
May 31 11:53:35 PM  
May 31 11:53:35 PM  User information: uid=0 euid=0 gid=0 egid=0
May 31 11:53:35 PM  
May 31 11:53:35 PM    warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
May 31 11:53:35 PM  [2022-05-31 17:53:35 +0000] [15] [ERROR] Connection in use: ('0.0.0.0', 6801)
May 31 11:53:35 PM  [2022-05-31 17:53:35 +0000] [15] [ERROR] Retrying in 1 second.
May 31 11:53:36 PM  
May 31 11:53:36 PM   -------------- celery@srv-cab5bdc41ls9f3cj3lug-kn-00001-deployment-6f9b5b8c6b-phjm2 v5.2.3 (dawn-chorus)
May 31 11:53:36 PM  --- ***** -----
May 31 11:53:36 PM  -- ******* ---- Linux-5.13.0-1025-aws-x86_64-with-glibc2.28 2022-05-31 17:53:36
May 31 11:53:36 PM  - *** --- * ---
May 31 11:53:36 PM  - ** ---------- [config]
May 31 11:53:36 PM  - ** ---------- .> app:         Essential Bot Tasks:0x7fe1c9c34040
May 31 11:53:36 PM  - ** ---------- .> transport:   redis://unkusr:**@redis-11269.c135.eu-central-1-1.ec2.cloud.redislabs.com:11269//
May 31 11:53:36 PM  - ** ---------- .> results:     redis://unkusr:**@redis-11269.c135.eu-central-1-1.ec2.cloud.redislabs.com:11269/
May 31 11:53:36 PM  - *** --- * --- .> concurrency: {min=5, max=10} (prefork)
May 31 11:53:36 PM  -- ******* ---- .> task events: ON
May 31 11:53:36 PM  --- ***** -----
May 31 11:53:36 PM   -------------- [queues]
May 31 11:53:36 PM                  .> celery           exchange=celery(direct) key=celery
May 31 11:53:36 PM  
May 31 11:53:36 PM  
May 31 11:53:36 PM  [tasks]
May 31 11:53:36 PM    . download_updater
May 31 11:53:36 PM    . ravager.celery_tasks.tasks.clean_database
May 31 11:53:36 PM    . ravager.celery_tasks.tasks.keep_heroku_alive
May 31 11:53:36 PM    . ravager.celery_tasks.tasks.restart_heroku
May 31 11:53:36 PM    . start_download
May 31 11:53:36 PM    . start_upload

**Comment by CoolFool** [comment]
Try this: [https://github.com/CoolFool/Ravager/issues/4#issuecomment-1139007285](https://github.com/CoolFool/Ravager/issues/4#issuecomment-1139007285)

**Comment by devillD** [comment]
Bot responded. But freezes at **processing** during download command.
celery log: https://pastebin.com/8z6D19wL
ravager log: https://pastebin.com/50vEPemT
aria log seems fine

**Comment by devillD** [comment]
Oky, not it's fixed

**Comment by CoolFool** [comment]
Ahhh I see the problem @devillD, You have to add heroku postgresql addon cause sqlite database doesn't work with heroku due to its ephemeral(temporary) storage
