### ISSUE TITLE
cant create redis server on heroku. 

### ISSUE THREAD

**Issue by devrajkaran** [CoolFool/Ravager#3]
so heroku doesn't allow you to create a redis server anymore if you dont link a credit card. Would it be possible to use a free redis database from [redis.com](https://redis.com/) instead. I tried it but it isnt working because it gives you a "Public endpoint" and a database name and password instead of a simple redis url.

**Comment by CoolFool** [comment]
The `REDIS_URL` will be in the form `redis://:<Default-user-password>@<public_endpoint>`
