### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by elricariocco** [CoolFool/Ravager#4]
Hello! I successfully deployed to Heroku but in the first download the app got banned (due to new heroku policy). So I decided to try and deploy on Render.com.
I edited the vars in  config.py and deployed to render... however this is showing in the logs 
![image](https://user-images.githubusercontent.com/91217900/170459906-bcc36ffb-5e7b-47af-96f1-fb078db730a7.png)

![image](https://user-images.githubusercontent.com/91217900/170460635-8538e799-2de4-4aad-8a1c-63f3f7bf03dd.png)

**Comment by CoolFool** [comment]
Can you send the full traceback in the second screenshot? Also can you access the filesystem? if yes please upload the log files

**Comment by elricariocco** [comment]
Here is the full traceback
![image](https://user-images.githubusercontent.com/91217900/170552280-653dc3dc-ef32-4100-828b-898163c5028d.png)
after this it goes back to the first picture and loops the same sequence of errors..
I don't think I can access the filesystem. :c

**Comment by elricariocco** [comment]
![image](https://user-images.githubusercontent.com/91217900/170604297-907eadac-b591-4b80-9fb5-f0d7d59b4ae8.png)

It is working now, thanks! I noticed that not all downloads are accepted though for example I tried a few magnets/torrent and the  bot was locked at "processing download" and never started whereas other direct link downloads were accepted just fine, but I guess that is a Render issue, probably blocking/blacklisting sites/words.
Anyways thanks for the help!
I hope u continue to add amazing features to improve your tool, great job!

**Comment by Topkek6969** [comment]
>    `STATE_SECRET_KEY` = generate it

> If you face any issues let me know

A noob question here, how to generate the state_secret_key? There's nothing much in the readme

P.S. Sorry if posted in wrong place.

**Comment by CoolFool** [comment]
I will look into adding health-check for docker,the feature kind of exists as /keep_alive endpoint for heroku.

**Comment by elricariocco** [comment]
I would like to learn how to do it.. I have another project (another bot) that works as intended but due to no healtcheck Render marks the deploy as failed after few mins and the bot stops working despite being fully functional.

**Comment by CoolFool** [comment]
Here are few resources if you want to learn
-  [https://docs.docker.com/engine/reference/builder/#healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck)
- [https://scoutapm.com/blog/how-to-use-docker-healthcheck](https://scoutapm.com/blog/how-to-use-docker-healthcheck)

Its pretty simple tbh, I just have to add something like `HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost:{PORT}/keep_alive || exit 1` to DOCKERFILE then build and test it

But right now I am busy with some stuff will fix it in few days

**Comment by CoolFool** [comment]
@elricariocco healthcheck has been added to dockerfile,rebuild and re-deploy and let me know if it works

**Comment by arjung24** [comment]
With free service, how much specs render.com gives??
Like ram, storage etc

Thanks in advance

**Comment by elricariocco** [comment]
> @elricariocco healthcheck has been added to dockerfile,rebuild and re-deploy and let me know if it works

Sadly my render account got terminated when I tried to redeploy your updated repo. I had been running the bot for 4 days so far (I had added /keep_alive to healthcheck var in render and also set up a cron-job that pinged myrenderurl/keep_alive just in case and that was enough. Now with the updated repo I made two new accounts and they just close while deploying. Weird.

**Comment by elricariocco** [comment]
> > With free service, how much specs render.com gives?? Like ram, storage etc
> > Thanks in advance
> 
> Here are the links explaining the limits of free resources:
> 
> 1. https://render.com/pricing
> 2. https://render.com/docs/free

![image](https://user-images.githubusercontent.com/91217900/171055798-13f32857-bbb2-4b7c-afc4-82b6298d59a7.png)

This is what gets reported by my bot when it comes to storage, I dont know if this is shared or something. (Im using free tier).
This the other repo I told you about, as you can see it works, but since it does not serve anything over https it  does not fullfil the condition of being a "web service" and deploy never ends. Render suggest that these kind of bots be deployed as "Background workers" but that requires credit card... So I'm guessing as long as it serves literally anything it should pass the "serving something over https" condition and therefore deploy would be successful.
I have a simple "Hello World" html I got from the internet but I have no idea how to make it be served as I am not a programmer.

**Comment by arjung24** [comment]
> > > With free service, how much specs render.com gives?? Like ram, storage etc
> > > Thanks in advance
> > 
> > 
> > Here are the links explaining the limits of free resources:
> > 
> > 1. https://render.com/pricing
> > 2. https://render.com/docs/free
> 
> ![image](https://user-images.githubusercontent.com/91217900/171055798-13f32857-bbb2-4b7c-afc4-82b6298d59a7.png)
> 
> This is what gets reported by my bot when it comes to storage, I dont know if this is shared or something. (Im using free tier). This the other repo I told you about, as you can see it works, but since it does not serve anything over https it does not fullfil the condition of being a "web service" and deploy never ends. Render suggest that these kind of bots be deployed as "Background workers" but that requires credit card... So I'm guessing as long as it serves literally anything it should pass the "serving something over https" condition and therefore deploy would be successful. I have a simple "Hello World" html I got from the internet but I have no idea how to make it be served as I am not a programmer.

Brother can u please share your telegram id. We need to talk.

**Comment by CoolFool** [comment]
> > > With free service, how much specs render.com gives?? Like ram, storage etc
> > > Thanks in advance
> > 
> > 
> > Here are the links explaining the limits of free resources:
> > 
> > 1. https://render.com/pricing
> > 2. https://render.com/docs/free
> 
> ![image](https://user-images.githubusercontent.com/91217900/171055798-13f32857-bbb2-4b7c-afc4-82b6298d59a7.png)
> 
> This is what gets reported by my bot when it comes to storage, I dont know if this is shared or something. (Im using free tier). This the other repo I told you about, as you can see it works, but since it does not serve anything over https it does not fullfil the condition of being a "web service" and deploy never ends. Render suggest that these kind of bots be deployed as "Background workers" but that requires credit card... So I'm guessing as long as it serves literally anything it should pass the "serving something over https" condition and therefore deploy would be successful. I have a simple "Hello World" html I got from the internet but I have no idea how to make it be served as I am not a programmer.

You can use flask and host it, refer this article [https://stackabuse.com/serving-static-files-with-flask/](https://stackabuse.com/serving-static-files-with-flask/)

**Comment by elricariocco** [comment]
I tried creating webserver using nginx in dockerfile, also tried using a python script and while both methods did serve the html file they somehow prevented the bot from running, as if serving the html was a different app itself. I can manage to either run the bot or serve the html, not both at the same time. I guess I'm too dumb for this. 
How did you create the /keep_alive for your app? I think that should work too as it worked for your app.
I'll give flask a try..thanks. And sorry for deviating the topic...Anyways I could prove that your app works in Render for anyone interested, although there's a chance to be banned due to it being a mirror tool.

**Comment by elricariocco** [comment]
> > I tried creating webserver using nginx in dockerfile, also tried using a python script and while both methods did serve the html file they somehow prevented the bot from running, as if serving the html was a different app itself. I can manage to either run the bot or serve the html, not both at the same time. I guess I'm too dumb for this. How did you create the /keep_alive for your app? I think that should work too as it worked for your app. I'll give flask a try..thanks. And sorry for deviating the topic...Anyways I could prove that your app works in Render for anyone interested, although there's a chance to be banned due to it being a mirror tool.
> 
> Please explain the process for deploying on render

https://github.com/CoolFool/Ravager/issues/4#issuecomment-1139007285

**Comment by arjung24** [comment]
Thanks

**Comment by CoolFool** [comment]
> I tried creating webserver using nginx in dockerfile, also tried using a python script and while both methods did serve the html file they somehow prevented the bot from running, as if serving the html was a different app itself. I can manage to either run the bot or serve the html, not both at the same time. I guess I'm too dumb for this. How did you create the /keep_alive for your app? I think that should work too as it worked for your app. I'll give flask a try..thanks. And sorry for deviating the topic...Anyways I could prove that your app works in Render for anyone interested, although there's a chance to be banned due to it being a mirror tool.

Ahh I see the problem, You can serve the file by editing main.py in ravager/main.py and adding a route (see flask tutorials for adding routes)

**Comment by carolynsteeves1** [comment]
Can you make an video showing how to make this on render? It would be very apreciated :D

**Comment by CoolFool** [comment]
> Can you make an video showing how to make this on render? It would be very apreciated :D

Sorry mate, Refer this https://github.com/CoolFool/Ravager/issues/4#issuecomment-1139007285

**Comment by carolynsteeves1** [comment]
> > Can you make an video showing how to make this on render? It would be very apreciated :D
> 
> Sorry mate, Refer this [#4 (comment)](https://github.com/CoolFool/Ravager/issues/4#issuecomment-1139007285)

ah ok, does render.com require an credit card for free service?

**Comment by CoolFool** [comment]
> > > Can you make an video showing how to make this on render? It would be very apreciated :D
> > 
> > 
> > Sorry mate, Refer this [#4 (comment)](https://github.com/CoolFool/Ravager/issues/4#issuecomment-1139007285)
> 
> ah ok, does render.com require an credit card for free service?

No, not afaik
