### ISSUE TITLE
[Suggestion] Add full list of shared drives

### ISSUE THREAD

**Issue by Topkek6969** [CoolFool/Ravager#5]
I have lot of shared drives on my google account and the bot only shows first few ones alphabetically. I had to rename my drive so that it would show up in the bot, it'd be great if you can just add folder id of the drive you want to add or show whole list of drives.

**Comment by CoolFool** [comment]
There should be a **next** button to basically go through all the shared drives 5 at a time

**Comment by Topkek6969** [comment]
> There should be a **next** button to basically go through all the shared drives 5 at a time

For me it just cycles through the same first 10 drives. Just confirmed by trying it again.

**Comment by devillD** [comment]
@CoolFool
Facing the same issue. The next button doesn't show all of the TDs

**Comment by CoolFool** [comment]
@Topkek6969 @devillD added a fix,re-deploy and let me know if it works

**Comment by Topkek6969** [comment]
> @Topkek6969 @devillD added a fix,re-deploy and let me know if it works

Alright, let me try.

**Comment by Topkek6969** [comment]
> > @Topkek6969 @devillD added a fix,re-deploy and let me know if it works
> 
> Alright, let me try.

@devillD @CoolFool It's fixed.

**Comment by Topkek6969** [comment]
Cool. Will try
