### ISSUE TITLE
'Error Occurred while handling request' while using download/upload

### ISSUE THREAD

**Issue by Topkek6969** [CoolFool/Ravager#6]
![Screenshot](https://user-images.githubusercontent.com/90697874/170870082-6e6f208d-c6df-4fb0-ae5d-7700afd1777c.png)

P.S. I did everything according to the steps given. In case it's something minor, i apologize, a newbie here :)

**Comment by Topkek6969** [comment]
Just noticed, the same error occurs even for abort command. Above logs are for when I try to download direct link while they are similar for magnet links too.

**Comment by CoolFool** [comment]
Can you restart the app? and send the full log by clicking on `save` by the bottom right after reproducing the error

**Comment by Topkek6969** [comment]
> Can you restart the app? and send the full log by clicking on `save` by the bottom right after reproducing the error

[ravagervala-bot-logs-1653832238642.txt](https://github.com/CoolFool/Ravager/files/8793449/ravagervala-bot-logs-1653832238642.txt)

Restarted the bot and used download command with a magnet link.

**Comment by CoolFool** [comment]
added a fix,re-deploy and let me know if it works

**Comment by Topkek6969** [comment]
> added a fix,re-deploy and let me know if it works

Alright.

**Comment by CoolFool** [comment]
> > Can you restart the app? and send the full log by clicking on `save` by the bottom right after reproducing the error
> 
> [ravagervala-bot-logs-1653832238642.txt](https://github.com/CoolFool/Ravager/files/8793449/ravagervala-bot-logs-1653832238642.txt)
> 
> Restarted the bot and used download command with a magnet link.

Deleting this comment cause it leaks your telegram bot token and database url
Please revoke your current token and get a new one

**Comment by CoolFool** [comment]
Deleted your log comment cause it leaked your telegram bot token and database url
Please revoke your current bot token as well as database url and get a new one

**Comment by Topkek6969** [comment]
> Deleted your log comment cause it leaked you telegram bot token and database url

Thanks, btw I don't know if I messed something or what but the bot isn't responding to any commands. heroku logs show that it starts alright but no output for any commands.

Edit : Nevermind, changed the bot like you suggested and it works fine now.

**Comment by CoolFool** [comment]
Does the shared drive selection menu work fine now?

**Comment by Topkek6969** [comment]
> Does the shared drive selection menu work fine now?

It does. So does the sys_info.

Edit: Awesome, mirroring working well now. Thanks a lot @CoolFool , it's rare to see a dev acknowledge issues and respond so quick :)

**Comment by CoolFool** [comment]
Haha thank you, I appreciate it :v: 



Feel free to create a new issue if you face any problems

**Comment by Topkek6969** [comment]
Can I keep the _keep_alive_ variable **false** and use external tools like cronjob for customized waking? I don't need the bot to stay alive while I sleep only to waste dynos.

**Comment by CoolFool** [comment]
Yes, I added that feature cause I was too lazy to use services like uptime robot

**Comment by Topkek6969** [comment]
> Yes, I added that feature cause I was too lazy to use services like uptime robot

Haha, cool. Have a great day!

**Comment by Topkek6969** [comment]
@CoolFool I'm still getting **POST** requests to my heroku from old bot token. Any idea?

`2022-05-29T17:00:45.826936+00:00 heroku[router]: at=info method=POST path="/2014201801:AAFQAA8AMyKYmeX6_IXQ_UDWs5KBsKQS47Y" host=ravagervala-bot.herokuapp.com request_id=9fc64f40-1147-4e2c-85bc-780a286ab6b9 fwd="91.108.6.136" dyno=web.1 connect=0ms service=1ms status=404 bytes=393 protocol=https`

**Comment by CoolFool** [comment]
Maybe telegram has two registered webhooks? Wait for a day and if it still occurs create a new instance

**Comment by Topkek6969** [comment]
> Maybe telegram has two registered webhooks? Wait for a day and if it still occurs create a new instance

new instance of?

Edit: No new request since past few mins, probably fixed :)
