### ISSUE TITLE
Allow listing bugged?

### ISSUE THREAD

**Issue by Topkek6969** [CoolFool/Ravager#8]
Even if `allowlist` is set to **false**, the bot still asks for user password.

**Comment by CoolFool** [comment]
should be fixed now, re-deploy and let me know

And thank you for reporting these bugs!

**Comment by Topkek6969** [comment]
> should be fixed now, re-deploy and let me know
> 
> And thank you for reporting these bugs!

Will redeploy after sometime, a bit busy right now
And you are welcome 😄

**Comment by Topkek6969** [comment]
It's fixed. 👍
